##
## EPITECH PROJECT, 2018
## cpp_rush2
## File description:
## Created by martin.januario@epitech.eu
##

SRC             =       ../Src/Parsing/Parsing.cpp	\
                        ../Src/Parsing/ErrorParsing.cpp	\
                        ../Src/Component/AbstractComponent.cpp	\
                        ../Src/Component/Chipset/CD4008BMS.cpp	\
                        ../Src/Component/Chipset/CD4011B.cpp	\
                        ../Src/Component/Chipset/CD4030C.cpp	\
                        ../Src/Component/Chipset/CD4069UBC.cpp	\
                        ../Src/Component/Chipset/CD4512B.cpp	\
                        ../Src/Component/Chipset/CD4514BC.cpp	\
                        ../Src/Component/Chipset/HCF4081B.cpp	\
                        ../Src/Component/Chipset/HEF4001B.cpp	\
                        ../Src/Component/Chipset/HEF4071B.cpp	\
                        ../Src/Component/Component/AndGate.cpp	\
                        ../Src/Component/Component/Clock.cpp	\
                        ../Src/Component/Component/FullAdderComponent.cpp	\
                        ../Src/Component/Component/Input.cpp	\
                        ../Src/Component/Component/NandGate.cpp	\
                        ../Src/Component/Component/NorGate.cpp	\
                        ../Src/Component/Component/NotGate.cpp	\
                        ../Src/Component/Component/OrGate.cpp	\
                        ../Src/Component/Component/RSNorLatchComponent.cpp	\
                        ../Src/Component/Component/XorGate.cpp	\
                        ../Src/Component/Component/Output.cpp	\
                        ../Src/Factory.cpp	\
                        ../Src/Interpretor.cpp \
                        ../Src/Executor.cpp	\
                        ../Src/Component/Chipset/MC14040B.cpp	\
                        ../Src/Component/Chipset/HC4017.cpp		\
                        ../Src/Component/Chipset/CD4013BC.cpp

SRC_OBJECT      =       test_and.cpp	\
			test_or.cpp	\
			test_nor.cpp	\
			test_nand.cpp	\
			test_not.cpp	\
			test_xor.cpp	\
			test_hef4001b.cpp	\
			test_fulladder.cpp	\
			test_cd4008bms.cpp	\
			test_cd4011b.cpp	\
			test_cd4030c.cpp	\
			test_cd4069ubc.cpp	\
			test_hef4071b.cpp	\
			test_hcf4081b.cpp	\
			test_rsnorlatch.cpp	\
			test_cd4512b.cpp	\
			ReportHook.cpp		\
			test_cd4514bc.cpp	\
			test_clock.cpp		\
			test_parsing.cpp

OBJ	=	$(SRC:.cpp=.o)	\
		$(SRC_OBJECT:.cpp=.o)

CPPFLAGS        =       -lcriterion -std=c++11 --coverage -lgcov -I ../Include/ -I ../Include/Chipset -I ../Include/Component -I ../Include/Parsing

GCDA	=	test_and.gcda	\
            test_or.gcda	\
            test_nor.gcda	\
            test_nand.gcda	\
            test_not.gcda	\
            test_xor.gcda	\
            test_hef4001b.gcda	\
            test_fulladder.gcda	\
            test_cd4008bms.gcda	\
            test_cd4011b.gcda	\
            test_cd4030c.gcda	\
            test_cd4069ubc.gcda	\
            test_hef4071b.gcda	\
            test_hcf4081b.gcda	\
            test_rsnorlatch.gcda	\
            test_cd4512b.gcda	\
            ReportHook.gcda		\
            test_cd4514bc.gcda	\
            test_clock.gcda	\
            test_parsing.gcda \
            ../Src/Component/AbstractComponent.gcda	\
            ../Src/Component/Chipset/CD4008BMS.gcda	\
            ../Src/Component/Chipset/CD4011B.gcda	\
            ../Src/Component/Chipset/CD4030C.gcda	\
            ../Src/Component/Chipset/CD4069UBC.gcda	\
            ../Src/Component/Chipset/CD4512B.gcda	\
            ../Src/Component/Chipset/CD4514BC.gcda	\
            ../Src/Component/Chipset/HCF4081B.gcda	\
            ../Src/Component/Chipset/HEF4001B.gcda	\
            ../Src/Component/Chipset/HEF4071B.gcda	\
            ../Src/Component/Component/AndGate.gcda	\
            ../Src/Component/Component/Clock.gcda	\
            ../Src/Component/Component/FullAdderComponent.gcda	\
            ../Src/Component/Component/Input.gcda	\
            ../Src/Component/Component/NandGate.gcda	\
            ../Src/Component/Component/NorGate.gcda	\
            ../Src/Component/Component/NotGate.gcda	\
            ../Src/Component/Component/OrGate.gcda	\
            ../Src/Component/Component/RSNorLatchComponent.gcda	\
            ../Src/Component/Component/XorGate.gcda	\
            ../Src/Component/Component/Output.gcda	\
            ../Src/Component/Chipset/MC14040B.gcda	\
            ../Src/Component/Chipset/HC4017.gcda	\
            ../Src/Component/Chipset/CD4013BC.gcda \
            ../Src/Factory.gcda	\
            ../Src/Interpretor.gcda \
            ../Src/Parsing/Parsing.gcda	\
            ../Src/Parsing/ErrorParsing.gcda	\
            ../Src/Executor.gcda

GCNO	=	test_and.gcno	\
            test_or.gcno	\
            test_nor.gcno	\
            test_nand.gcno	\
            test_not.gcno	\
            test_xor.gcno	\
            test_hef4001b.gcno	\
            test_fulladder.gcno	\
            test_cd4008bms.gcno	\
            test_cd4011b.gcno	\
            test_cd4030c.gcno	\
            test_cd4069ubc.gcno	\
            test_hef4071b.gcno	\
            test_hcf4081b.gcno	\
            test_rsnorlatch.gcno	\
            test_cd4512b.gcno	\
            ReportHook.gcno		\
            test_cd4514bc.gcno	\
            test_clock.gcno	\
            test_parsing.gcno \
            ../Src/Component/AbstractComponent.gcno	\
            ../Src/Component/Chipset/CD4008BMS.gcno	\
            ../Src/Component/Chipset/CD4011B.gcno	\
            ../Src/Component/Chipset/CD4030C.gcno	\
            ../Src/Component/Chipset/CD4069UBC.gcno	\
            ../Src/Component/Chipset/CD4512B.gcno	\
            ../Src/Component/Chipset/CD4514BC.gcno	\
            ../Src/Component/Chipset/HCF4081B.gcno	\
            ../Src/Component/Chipset/HEF4001B.gcno	\
            ../Src/Component/Chipset/HEF4071B.gcno	\
            ../Src/Component/Component/AndGate.gcno	\
            ../Src/Component/Component/Clock.gcno	\
            ../Src/Component/Component/FullAdderComponent.gcno	\
            ../Src/Component/Component/Input.gcno	\
            ../Src/Component/Component/NandGate.gcno	\
            ../Src/Component/Component/NorGate.gcno	\
            ../Src/Component/Component/NotGate.gcno	\
            ../Src/Component/Component/OrGate.gcno	\
            ../Src/Component/Component/RSNorLatchComponent.gcno	\
            ../Src/Component/Component/XorGate.gcno	\
            ../Src/Component/Component/Output.gcno	\
            ../Src/Component/Chipset/MC14040B.gcno	\
            ../Src/Component/Chipset/HC4017.gcno	\
            ../Src/Factory.gcno	\
            ../Src/Interpretor.gcno \
            ../Src/Parsing/Parsing.gcno	\
            ../Src/Parsing/ErrorParsing.gcno	\
            ../Src/Executor.gcno	\
            ../Src/Component/Chipset/CD4023BC.gcno

GCOV	=	$(shell find ../ -type f -name "*.gcov")

NAME    	=       test

all:		$(NAME)

$(NAME):	$(OBJ)
			g++ -o $(NAME) $(OBJ) $(CPPFLAGS)

clean:
			rm -f $(OBJ)
			rm -f $(GCDA)
			rm -f $(GCNO)
			rm -f $(GCOV)
			rm -f $(shell find . -type f -name "*.html")
			rm -f $(shell find . -type f -name "*.png")
			rm -f $(shell find . -type f -name "*.css")
			rm -f app.info

coverage:
		lcov --no-external --directory ../Src --directory . --capture --output-file app.info && genhtml app.info && firefox index.html

fclean: clean
			rm -f $(NAME)

re:         fclean all

.PHONY:     all clean re fclean $(NAME)
